### ISSUE TITLE
r2pm -ci rlang-python not installed or due to some other issue, not able to load r2ai in r2 repl

### ISSUE THREAD

**Issue by Xplo8E** [radareorg/radare2-rlang#39]
I was trying to use r2ai, the installation process is correctly done and I was able to use it with `r2pm -r r2ai`. but to use it in r2 repl I have to install rlang-python, earlier when installing r2ai I installed it but it was asking again to run `r2pm -ci rlang-python`.

so I installed it again by running that command (I already tried more than 5 times running it)

OUTPUT:

```
r2pm -ci rlang-python
INFO: Cleaning rlang-python
INFO: Using r2-5.8.9 and r2pm-5.8.9
INFO: Cleaning rlang-python
INFO: git clone --depth=10 --recursive https://github.com/radareorg/radare2-rlang /Users/apple/.local/share/radare2/r2pm/git//rlang-python
Cloning into '/Users/apple/.local/share/radare2/r2pm/git//rlang-python'...
remote: Enumerating objects: 208, done.
remote: Counting objects: 100% (208/208), done.
remote: Compressing objects: 100% (179/179), done.
remote: Total 208 (delta 25), reused 162 (delta 22), pack-reused 0
Receiving objects: 100% (208/208), 1.42 MiB | 1.40 MiB/s, done.
Resolving deltas: 100% (25/25), done.
INFO: Starting install for rlang-python
INFO: SCRIPT=<<EOF
INFO: 	[ -z python-config ] && \
		echo "python-config binary for python3 not found," \
		"please specify via PYTHON_CONFIG environment variable" && exit 1
	./configure --prefix=${R2PM_PREFIX}
	cd python
	${MAKE} clean || exit 1
	${MAKE} || exit 1
	${R2PM_SUDO} ${MAKE} install R2_PLUGIN_PATH="${R2PM_PLUGDIR}" R2PM_PLUGDIR="${R2PM_PLUGDIR}" || exit 1
INFO: EOF
checking build system type... x86_64-unknown-darwin
checking host system type... x86_64-unknown-darwin
checking target system type... x86_64-unknown-darwin
checking for working directories... current
using prefix '/Users/apple/.local/share/radare2/prefix'
checking for c compiler... gcc
checking for pkg-config... /usr/local/bin/pkg-config
Using PKGCONFIG: /usr/local/bin/pkg-config
checking pkg-config flags for r_core... yes
creating ./config.mk
cleaning temporally files... done

Final report:
 - PREFIX = /Users/apple/.local/share/radare2/prefix
rm -f *.dylib *. *.o
rm -rf *.dSYM
cc -I/usr/local/include/libr -I/usr/local/Cellar/capstone/5.0.1/include/capstone -I/usr/local/include/libr -DPREFIX=\"/Users/apple/.local/share/radare2/prefix\" -g -I/usr/local/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/include/python3.12 -I/usr/local/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/include/python3.12 -DPYVER=3   -c -o python.o python.c
In file included from python.c:4:
In file included from /usr/local/include/libr/r_core.h:6:
In file included from /usr/local/include/libr/r_main.h:6:
In file included from /usr/local/include/libr/r_types.h:12:
/usr/local/include/stdlib.h:134:25: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
double   atof(const char *);
                         ^
/usr/local/include/stdlib.h:134:25: note: insert '_Nullable' if the pointer may be null
double   atof(const char *);
                         ^
                          _Nullable
/usr/local/include/stdlib.h:134:25: note: insert '_Nonnull' if the pointer should never be null
double   atof(const char *);
                         ^
                          _Nonnull
/usr/local/include/stdlib.h:135:22: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
int      atoi(const char *);


--------------OUTPUT STRIPPED------------


                                  ^
/usr/local/include/signal.h:108:31: note: insert '_Nullable' if the pointer may be null
int     sigvec(int, struct sigvec *, struct sigvec *);
                                  ^
                                   _Nullable
/usr/local/include/signal.h:108:31: note: insert '_Nonnull' if the pointer should never be null
int     sigvec(int, struct sigvec *, struct sigvec *);
                                  ^
                                   _Nonnull
/usr/local/include/signal.h:108:48: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
int     sigvec(int, struct sigvec *, struct sigvec *);
                                                   ^
/usr/local/include/signal.h:108:48: note: insert '_Nullable' if the pointer may be null
int     sigvec(int, struct sigvec *, struct sigvec *);
                                                   ^
                                                    _Nullable
/usr/local/include/signal.h:108:48: note: insert '_Nonnull' if the pointer should never be null
int     sigvec(int, struct sigvec *, struct sigvec *);
                                                   ^
                                                    _Nonnull
215 warnings generated.
ld: warning: ignoring duplicate libraries: '-ldl', '-lr_asm', '-lr_core', '-lr_io', '-lr_util'
mkdir -p //Users/apple/.local/share/radare2/plugins
rm -f //Users/apple/.local/share/radare2/plugins/`ls *.dylib`
[ -n "`ls *.dylib`" ] && cp -f *.dylib //Users/apple/.local/share/radare2/plugins || true

```

it was showing it installed in the plugin directory

```
$ ls .local/share/radare2/plugins/
io_frida.dylib    lang_python.dylib r2ai.py
```

but still I am getting this error in r2 repl

```
[0x100007ea8]> #!pipe r2ai
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
r2ai plugin cannot be loaded. Run `r2pm -ci rlang-python`
[0x100007ea8]>
```

**Comment by trufae** [comment]
Thats probably because the versipn of python that u compiled the plugin is mot the same as the one used by r2ai. Rhe plugin when loaded creatss the r2ai command. So u dont need to call it with #!pipe

**Comment by Xplo8E** [comment]
i used python3 (3.12) for both r2ai and for rlang-python too

fyi with `R2_DBEUG=1`

```
DEBUG: Loading /usr/local/lib/radare2/5.8.9/io_shm.dylib
DEBUG: Cannot find symbol 'radare_plugin' in library '/usr/local/lib/radare2/5.8.9/io_shm.dylib'
DEBUG: Skip/Ignore /Users/apple/.local/share/radare2/plugins/r2ai.py
DEBUG: Loading /Users/apple/.local/share/radare2/plugins/lang_python.dylib
DEBUG: PLUGIN LOADED 0x6000020d48c0 fcn 0x10c4f4d50
DEBUG: Cannot open directory '/usr/local/lib/radare2-extras/5.8.9'
DEBUG: Cannot open directory '/usr/local/lib/radare2-bindings/5.8.9'
DEBUG: PLUGIN LOADED 0x6000020d46e0 fcn 0x10c4f4b60
DEBUG: RCoreCmd: =!
DEBUG: [mach0] load dynamic linker
```

rlang-python plugin is loaded but r2ai was skipped

**Comment by trufae** [comment]
I fixed r2ai to make it work via r2pipe. you can now do "#!pipe python main.py your query goes here"

The plugin is skipped because the it's not ending with .dylib. thats the check that is failing there. But once the lang_python.dylib plugin is loaded it should be loaded after that. you can run the Lc command to see if it's listed.

Also, i have added some logs when loading python plugins so you may see somethiing more if you r2pm -ci rlang-python

**Comment by Xplo8E** [comment]
@trufae  yeah, now it was working fine, I tried with gpt4, in r2ai except auto mode remaining working fine, auto mode giving `NameError: name 'r2lang' is not defined`. but rlang-python is already installed, do I missing something?


```
[0x100007ea8]> '$r2ai=#!pipe r2ai
DEBUG: RCoreCmd: pg
DEBUG: RCoreCmd: '$r2ai=#!pipe r2ai
[0x100007ea8]> $r2ai "' list the imports for this program"
DEBUG: RCoreCmd: pg
DEBUG: RCoreCmd: $r2ai "' list the imports for this program"
DEBUG: RCoreCmd: #!pipe r2ai "' list the imports for this program"
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.

Running ii
Traceback (most recent call last):
  File "/Users/apple/r2ai/r2ai/interpreter.py", line 639, in chat
    self.respond()
  File "/Users/apple/r2ai/r2ai/interpreter.py", line 801, in respond
    response = auto.chat(self)
               ^^^^^^^^^^^^^^^
  File "/Users/apple/r2ai/r2ai/auto.py", line 204, in chat
    process_streaming_response(interpreter, response)
  File "/Users/apple/r2ai/r2ai/auto.py", line 173, in process_streaming_response
    process_tool_calls(interpreter, tool_calls)
  File "/Users/apple/r2ai/r2ai/auto.py", line 104, in process_tool_calls
    res = r2lang.cmd(args["command"])
          ^^^^^^
NameError: name 'r2lang' is not defined
```

<img width="1374" alt="Screenshot 2024-03-28 at 10 19 44 AM" src="https://github.com/radareorg/radare2-rlang/assets/55936553/df3e6062-3cc9-4d92-80cb-6fb70b55581c">


do I need to open a new issue in the r2ai repo for this one instead of posting this query here?

**Comment by trufae** [comment]
Did u git pull r2ai. Auto mode works with r2pipe too

**Comment by Xplo8E** [comment]
sorry i forgot that, but even after updating to latest commit, it giving different error with alias `#!pipe r2ai`

and without pipe i.e r2ai it is not giving error 

<img width="1398" alt="Screenshot 2024-03-28 at 11 43 50 AM" src="https://github.com/radareorg/radare2-rlang/assets/55936553/a23e7d22-a4d9-4ed4-a5cf-175ddd92a31b">

the plugins also loaded

<img width="1215" alt="Screenshot 2024-03-28 at 11 48 23 AM" src="https://github.com/radareorg/radare2-rlang/assets/55936553/5760eed5-8bec-44c8-95da-82d483e4d38d">

**Comment by Xplo8E** [comment]
it was fixed with `pip3 install r2pipe`, thanks for helping me out.

**Comment by trufae** [comment]
Cool!
